### ISSUE TITLE
Allow either moxi_works_agent_id or agent_uuid in Contact.search

### ISSUE THREAD

**Issue by nickblumenthal** [moxiworks-platform/moxiworks-ruby#12]
According to the docs, either `moxi_works_agent_id` or `agent_uuid` are required when using `Contact.search`.  However, it looks like https://github.com/moxiworks-platform/moxiworks-ruby/blob/master/lib/moxiworks_platform/contact.rb#L540 is only accepting the `moxi_works_agent_id`.  Anyway we could have the `agent_uuid` as another option?

**Comment by tres** [comment]
Hi @nickblumenthal , 

Sorry for the delay here. We'll take a look at getting this pulled into the next release of the gem. 

Tres
