### ISSUE TITLE
'rest-client' development dependency

### ISSUE THREAD

**Issue by ncavig** [moxiworks-platform/moxiworks-ruby#2]
`spec.add_development_dependency 'rest-client'` should be changed to `spec.add_dependency 'rest-client'` in the gemspec since it's a hard dependency of this gem. If it's not in your apps Gemfile you'll get the following error 

```
LoadError: cannot load such file -- rest-client
```

**Comment by tres** [comment]
Thanks, Nicolas!

I'll update the gemspec & push an updated version.

**Comment by tres** [comment]
fixed in https://github.com/moxiworks-platform/moxiworks-ruby/commit/a45e3e3b8847bb49781f6e4528db400fe5347751

pushed to rubygems.org as 0.12.1

https://rubygems.org/gems/moxiworks_platform/versions/0.12.1

Thanks again for your report, Nicolas! Let us know if there's anything else that you find.

**Comment by ncavig** [comment]
Appreciate it!
