### ISSUE TITLE
Unnecessary required option

### ISSUE THREAD

**Issue by nickblumenthal** [moxiworks-platform/moxiworks-ruby#7]
Hi @tres -

According to the docs, `moxi_works_company_id` is the only required parameter for `MoxiworksPlatform::Agent.search`.  Currently you require an `updated_since` param too.  Anyway you could remove that?

Here's the line:
https://github.com/moxiworks-platform/moxiworks-ruby/blob/master/lib/moxiworks_platform/agent.rb#L343

Our use case is actually querying for deactivated agents and we would be using `deactivated_since` instead of `updated_since`

I wanted to just submit a PR, but I don't have enough time to figure out how to get the specs working with VCR and this seems pretty easy.

Thanks!

**Comment by nickblumenthal** [comment]
Awesome!  Thanks for the quick reply!

**Comment by tayleighr** [comment]
@nickblumenthal please see the requested updates in version 0.13.14. Thanks for reaching out!

**Comment by nickblumenthal** [comment]
Awesome, meant to mention this last week, but I appreciate you guys fixing this so quickly!
